# -*- coding: utf-8 -*-
"""populationdatacleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ie6lgjftSWVPb3lh_DucM9sE98NYfLEC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Population_Clean = pd.read_excel('/content/4_6007878812891618215.xlsx')
Population_Clean.head()

Population_Clean["Date"] = pd.to_datetime(Population_Clean["Date"])

Population_Clean[["Country", "City", "PlaceName"]] = \
    Population_Clean[["Country", "City", "PlaceName"]].astype(str)
Population_Clean[["Members", "Male", "Female", "Room", "Flat", "House", "Tent"]] = \
    Population_Clean[["Members", "Male", "Female", "Room", "Flat", "House", "Tent"]].astype("Int64")

Population_Clean["Country"] = Population_Clean["Country"].str.strip()
Population_Clean["City"] = Population_Clean["City"].str.strip()
Population_Clean["PlaceName"] = Population_Clean["PlaceName"].str.strip()

housing_cols = ['Room', 'Flat', 'House', 'Tent']
Population_Clean[housing_cols] = Population_Clean[housing_cols].fillna(0)

Population_Clean = Population_Clean.dropna(how='all')
Population_Clean.duplicated().sum()
Population_Clean = Population_Clean.drop_duplicates()

#12
Population_Clean["Gender_Validation"] = "Review"

Population_Clean.loc[
    Population_Clean["Members"] == Population_Clean["Male"] + Population_Clean["Female"],
    "Gender_Validation"
] = "OK"
Population_Clean[["Members", "Male", "Female", "Gender_Validation"]].head()

#13
Population_Clean["Date"] = pd.to_datetime(Population_Clean["Date"])

Population_Clean["Year"] = Population_Clean["Date"].dt.year
Population_Clean["Month"] = Population_Clean["Date"].dt.month
Population_Clean[["Date", "Year", "Month"]].head()

Population_Clean.to_excel("population_cleaned.xlsx", index=False)
from google.colab import files

files.download("population_cleaned.xlsx")